### ISSUE TITLE
Wireframe - Criar design da Página de detalhamento de benefícios

### ISSUE THREAD

**Issue by sandrosodrenunes** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial#12]

**Comment by diletronics** [comment]
Olá Sandro Conforme combinamos estou trabalhando com a página no sigma.Adilmar Moreira(31)99890-5272Em 5 de abr. de 2024, à(s) 15:28, Sandro Sodré Nunes ***@***.***> escreveu:﻿
Closed #12 as completed.

**Comment by sandrosodrenunes** [comment]
Ok
