### ISSUE TITLE
Criar design da Página de Validar Benefícios

### ISSUE THREAD

**Issue by marcotuliocnd** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial#4]
- Formulário de anamnese para ver os beneficios que se adequam ao meu perfil

**Comment by bugbountywithmarco** [comment]
![Validar Beneficios 1](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/8e6365b5-6616-4c0c-bc7f-42cf5bb850c4)
![Validar Beneficios 2](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/d24b1795-fd3c-4910-91f1-e05ad507c0d3)
![Validar Beneficios 3](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/30c53732-f8d4-4a14-972e-48cfe98f637f)
![Validar Beneficios 4](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/2c597cfb-5ca2-491b-ab5e-317626ad83fd)
![Validar Beneficios 5](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/1b6e5d38-1075-46ab-b62c-326923d68d8a)
![Validar Beneficios 6](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe1-t2-infosocial/assets/8672242/98c553d8-3ba6-476e-8638-91cbc8a058ad)
